import type { Metadata } from "next";
import "./globals.css";
import { Bai_Jamjuree, Montserrat } from "next/font/google";
import Header from "@/components/localComponents/header";
import Footer from "@/components/localComponents/footer";

// Load Bai Jamjuree font
const baiJamjuree = Bai_Jamjuree({
  subsets: ["latin"],
  weight: ["200"],
});
const playpenSansDeva = Montserrat({
  subsets: ["latin"],
  weight: ["200"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${baiJamjuree.className} antialiased p-4 space-y-8 `}>
        <Header />

        {children}
        <Footer />
      </body>
    </html>
  );
}
